export enum ENVKEYS {
  APPPORT = 'APPPORT',
  MYSQL_ROOT_PASSWORD = 'MYSQL_ROOT_PASSWORD',
  MYSQL_DATABASE = 'MYSQL_DATABASE',
  MYSQL_USER = 'MYSQL_USER',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_SYNCDB = 'MYSQL_SYNCDB',
}

export enum GETTERTYPES {
  STRING = 'STRING',
  BOOLEAN = 'BOOLEAN',
  NUMBER = 'NUMBER',
}
